export const prodGallImages =[{priority: '0', 
                    full_image:  "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_main.jpg",
                    large_image:  "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_big.jpg",
                    medium_image:  "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672.jpg"},
                    {priority: '1',
                     small_image: "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_small.jpg",
                     full_image: "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_2main.jpg",
                     large_image: "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_2big.jpg",
                     medium_image: "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_2.jpg"}];
                    // (priority = 2,
                    // small_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_2small.jpg",
                    // full_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_3main.jpg",
                    // large_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_3big.jpg",
                    // medium_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_3.jpg"),
                    // (priority = 3,
                    // small_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_3small.jpg",
                    // full_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_4main.jpg",
                    // large_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_4big.jpg",
                    // medium_image = "http://opt.brain.com.ua/static/images/prod_img/7/2/U0200672_4.jpg")];